### ISSUE TITLE
Create a release for better reference from build tools

### ISSUE THREAD

**Issue by digitalLumberjack** [mortaca/RGB-Pi#1]
Hi, we build recalbox with buildroot and we prefere reference a release than a commit id for our build tool. Could you create a release of RGB-Pi please ?

**Comment by mortaca** [comment]
Done

**Comment by digitalLumberjack** [comment]
Sorry dude but rgb-pi_overlay cannot be a release version.

You should use v1.0.0 as a tag name in order to prevent future versions :)

**Comment by mortaca** [comment]
Ok I add v0.1 to the end.
