### ISSUE TITLE
[Feature Request] Screen Utility to support 480p, 720p

### ISSUE THREAD

**Issue by modology** [mortaca/RGB-Pi#16]
Currently only 240p and 270p are supported for Front End resolution

Would be nice if users can choose 480p and 720p.

Also allow users to choose aspect ratio between 4:3 and 16:9   ---> i have a widescreen bvm that can supports up to 1080i, 720p. Having this option would be a plua

**Comment by mortaca** [comment]
480p and 720p over SCART? This simply does not exist, those formats are 31Khz and need a VGA or HDMI connector. 

The RGB-Pi cable is thinked for only 15Khz resolutions over scart plug, if you are using VGA666 please do not comment if you are not using the cable for which the software is developed.
