### ISSUE TITLE
[Improvement] Config.txt editor

### ISSUE THREAD

**Issue by modology** [mortaca/RGB-Pi#17]
Issue:
- There are no instructions on screen on which butons can do what. Users can accidentallty delete text and save it, mess up all the resolution
- There are no on screen keyboard, impossible to edit text if users only use joypad

Suggestions:
- Show the legends of each hot key at the bottom of the screen so that users know which button combination can do..
- Detect if the keyboard is connected then dont show the Onscreen keyboard
- If keyboard is not connected, display on screen keyboard so that users can still edit it
- Please implemen Reset To Default option just incase users mess up config file

**Comment by mortaca** [comment]
Thank you for the suggestions but it is not an application that deserves so many hours of development, in fact maybe in future versions it is eliminated, it is a aplication made for development purposes and many people are using it to comfortably configure their vga666...
