### ISSUE TITLE
Excited for the new release - wondered if it will automatically scale vertical games on horiz display

### ISSUE THREAD

**Issue by YanikTheYak** [mortaca/RGB-Pi#18]
Hi
Firstly, I love the cable - really pleased with how it works in my CRT arcade machine :)
Really looking forward to the new release!!

Just wondered, I notice some rotate features being added. 
I have a Horizontal display, but play a mix of horiz and vert games (mainly shmups), but right now have to fiddle with the settings to make a vert game play scaled. Since there are a lot in MAME, I've only changed a few.
Just wondered if RGB-Pi can do this automatically (or if this is something being added in the next release?) 
I apologise if it already does this and I've set it up wrong!

Keep up the great work.
Ian

**Comment by mortaca** [comment]
This option is now available on ScreenUtility, you need to select the option, "TATE games rotation" to -90 and enjoy :) The best to play in this mode is advancemame, this give the best scalation results.
