### ISSUE TITLE
weird resolution bugs

### ISSUE THREAD

**Issue by modology** [mortaca/RGB-Pi#19]
Please check the video for detaila
https://youtu.be/U1PJs0PyyP8

**Comment by mortaca** [comment]
Try this development version of the next release:

http://www.mortaca.com/rgb-pi/downloads/41Final.img.xz

**Comment by modology** [comment]
been running for few days. It seems the issue has not happened again however i will keep testing out for few more weeks

**Comment by mortaca** [comment]
Ok perfect, please if you can delete the video with the YT bug to avoid confusion.
