### ISSUE TITLE
[Suggestion] New theme for RGB-Pi Screen Utility

### ISSUE THREAD

**Issue by modology** [mortaca/RGB-Pi#20]
Please check the mockup here:
https://i.imgur.com/ymB5fkc.png

Improvement Suggestion:
For certain switch that only has value of 1 and 0, I think it's much clearer to use label ON and OFF

**Comment by mortaca** [comment]
I take your idea to make the theme for EasyNetplay, the new function to play online, The fact of using 0 or 1 is for reasons of greater simplicity in programming, the theme of SU is inspired by Commodore64 and there are many users happy with this I can not change it, but you have a theme like you like in the EasyNetplay.

![image](https://user-images.githubusercontent.com/8557406/42136274-b8ecf022-7d58-11e8-89db-8aba5e7fbee2.png)
