### ISSUE TITLE
[Suggestion] Add some new theme optimised for 240p

### ISSUE THREAD

**Issue by modology** [mortaca/RGB-Pi#22]
Aside from three default included themes, would you consider to include some extra themes that are optimised for 240p mode ?

Some of the good 240p themes are:

**TFT Theme (Optimised for 240p)**
https://github.com/anthonycaccese/es-theme-tft

**And many other 240p themes are included in this link**
http://strike-devices.net/index.php/pi2scart/retropie-or-pi2scart/themes-for-retropie-using-pi2scart-or-pi2jamma/

**Comment by mortaca** [comment]
It is very interesting new themes but I can not offer and maintain so many, each user must install them on their own.
