### ISSUE TITLE
Composite Video or Luma Sync from Composite Video Port

### ISSUE THREAD

**Issue by MarkOZLAD** [mortaca/RGB-Pi#23]
Would it be possible to get the Pi to also output Composite Video or Luma to use as alternative sync methods?  I modify televisions for RGBS and some prefer Luma or Composite video instead of Composite Sync,

Would be ok if it outputted this composite video or luma for sync from the Composite video 3.5mm port in parallel with the existing csync through GPIO.

**Comment by mortaca** [comment]
It is impossible to take out video composed by the GPIO, I am investigating new options to do this with other hardware but with the current one it is not possible.
