### ISSUE TITLE
[Maldita Castila game special build] sync issue on bvm

### ISSUE THREAD

**Issue by modology** [mortaca/RGB-Pi#25]
i assume that the custok version of Maldita Castila game is an old version which still has some sync issue on sony bvm.

Would be able to have a newer version of maldita castilla game that solves the sync issue?

**Comment by mortaca** [comment]
Edit the config.txt and play with this value:

`hdmi_timings=319 1 20 20 **35** 217 1 15 15 16 0 0 0 60 0 6400000 1`

Try with 36,37,38...

**Comment by mortaca** [comment]
I can close the issue?
