### ISSUE TITLE
retroTINK S-Video support (black & white picture)

### ISSUE THREAD

**Issue by lbutler41** [mortaca/RGB-Pi#27]
I'm currently working on a 240p setup to use S-Video output with retroTINK and the RGB-Pi image. I've successfully flashed a disk and am using a config.txt file provided by retroTINK's creator. The RGB-Pi OS boots up correctly with all menus accessible, but picture is black & white in both games and menus. Any help would be appreciated.

Config:

hdmi_timings=450 1 50 30 90 270 1 1 1 30 0 0 0 50 0 9600000 1 
display_rotate=0

audio_pwm_mode=2
disable_audio_dither=1

disable_overscan=1

hdmi_drive=2

config_hdmi_boost=0

hdmi_force_hotplug=1

boot_delay=3

disable_splash=1

# Overclock
gpu_mem_256=128
gpu_mem_512=256
gpu_mem_1024=512

avoid_safe_mode=1

dtoverlay=pi3-disable-bt-overlay

dtparam=audio=on
#dtoverlay=pwm-2chan,pin=18,func=2,pin2=19,func2=2

dtoverlay=dpi24
enable_dpi_lcd=1
display_default_lcd=1
dpi_output_format=519
dpi_group=2
dpi_mode=87

kernel=zImage
overscan_scale=0

**Comment by mortaca** [comment]
We only support our hardware.
