### ISSUE TITLE
Sync issues on Sony BVM

### ISSUE THREAD

**Issue by lankg01** [mortaca/RGB-Pi#28]
Hi there,
I am having sync issues when launching a game on my Sony BVM (BVM-D20F1A). EmulationStation menu is fine but every time I try to launch a game my screen losses sync. I have tried switching my monitor's sync from external to internal to no avail.

I am using a Raspberry Pi 3b+ with the Beta 1.2 image, and I'm connecting it to my BVM via a BnC adapter. 

Thank you heaps for your help.

Regards
Christian

**Comment by mortaca** [comment]
Solved on the new OS
