### ISSUE TITLE
Not supported on Raspberry Pi 4

### ISSUE THREAD

**Issue by squidrpi** [mortaca/RGB-Pi#30]
Plug the cable in, copy the rgb-pi.dtbo to /boot/overlays and add settings in config.txt (same as RPi3) but no image appears on the CRT.

Is this a software issue or hardware incompatibility?

**Comment by rtomasa** [comment]
There is something you are doing wrong because it has been already tested in the latest Raspbian Buster and  it was working fine.

**Comment by squidrpi** [comment]
On Buster with Raspberry Pi 4?
Followed the instructions in https://github.com/mortaca/RGB-Pi/blob/master/README.md but I get a blank screen.

**Comment by rtomasa** [comment]
Yes Buster is the only supported for Pi4. Following the instructions also and worked fine. If still not working, try commenting out the 2 lines in the [pi4] section of the cfg related to the new video driver but do note that I was able to make It work without this change.

**Comment by squidrpi** [comment]
Yes tried all that. Doesn't work on Pi3 either with this Buster image. I'll wait a bit for this to all mature. Don't want to keep unplugging the cable incase I break it.

**Comment by squidrpi** [comment]
Tried with a new Buster image and added the normal rgp-pi to config.txt and it now works on the Pi4! It must have been because it was an early Buster image or something got messed up on that installation.
