### ISSUE TITLE
Limited set of characters available in WiFi Name

### ISSUE THREAD

**Issue by rgavril** [mortaca/RGB-Pi#35]
My wifi network contains an apostrophe('), which is very common on how apple devices generate their wifi network name (ex: Razvan's iPhone, Razvan's Airport)

Right now is impossible to connect to my wifi network because I can't input, with neither joystick or keyboard, the name of my wifi network.

Changing the name of the wifi network is a pain cause I need to reconfigure all my iot devices.

I'm using RGB-Pi OS (Beta)

**Comment by mortaca** [comment]
Solved
