### ISSUE TITLE
Missing important info in game list after scraping

### ISSUE THREAD

**Issue by damdai** [mortaca/RGB-Pi#42]
After scraping, important information from the original filenames are missing, such as revision, region, and disc number (possibly anything in parenthesis). See BEFORE and AFTER below for example.

**BEFORE**
Xenogears (Japan) (Disc 1)
Xenogears (Japan) (Disc 2)

**AFTER**
Xenogears
Xenogears

**Comment by mortaca** [comment]
This is the normal operation of the scrapper in all systems, to keep your custom name do not do scrape use the custom scrape that the system has, you have the instructions in the information section of the system itself
