### ISSUE TITLE
SNES defaults to mono

### ISSUE THREAD

**Issue by squidrpi** [mortaca/RGB-Pi#57]
Audio output for SNES defaults to DSP Plugin Crystalizer(Mono). Should be stereo. Version FINAL 1.2 20200925

**Comment by rtomasa** [comment]
Presets are global not system specific.
Audio must be mono by default for max compatibility with all TVs (99% TVs < 20"), otherwise you miss one complete audio channel.
In any case we are now in v1.4 of the OS which does not have those presets anymore.
