### ISSUE TITLE
Key step missing from "Adding ROMs" Wiki section (no direction to "search games" to have system recognize the games)

### ISSUE THREAD

**Issue by Dochartaigh** [mortaca/RGB-Pi#70]
If you are no longer tracking tickets here hopefully somebody will let me know (last issue posted is from 5 months ago which is why I ask... also PLEASE let me know where to ask questions/post issues then: Discord AND Telegram are NOT useful... maybe 1 out 4 questions I post there gets an answer... and they're simple things...).

Anyway, just wanted to let you know you are missing a KEY step in the "Adding ROMSs" section of your Wiki. You never told people they have to select "Search Games" after they load their games in order for them to show up. Without this step people can not play a single game...

That isn't a logical option to choose either - on RetroArch for example 'search games'  will search all your game names for the one you just typed in... that's why I never thought to hit that option to LOAD these games into the playlists - as that just wasn't logical to me (or many other people).

![Adding-ROMs-RGB-Pi-Wiki](https://user-images.githubusercontent.com/23370177/156454335-60b2d1fb-b03f-444f-aba1-68051e287495.png)

**Comment by emotionless-engine** [comment]
Someone listened and added another section at the bottom of page.

Thanks guys.

**Comment by Dochartaigh** [comment]
Yeah!!  Thank you to whoever did this. I already figured it out but hope it'll help others! (as others were lost with this who I saw post about the same issue on your Discord!).
