### ISSUE TITLE
Samba share doesn't work

### ISSUE THREAD

**Issue by Calprainn** [mortaca/RGB-Pi#80]
Both with OS 4 Alpha 19 or the new Alpha 20, the samba share does not work for me. No matter if I am connected over Ethernet or Wi-Fi. If I type smb://IP on my Mac or with Windows \\IP I get no connection. It can't be my network, SSH and SFTP works fine over the Ethernet/Wi-Fi IPs.

**Comment by rtomasa** [comment]
Samba is not supported anymore. Only SFTP

**Comment by Calprainn** [comment]
Okay, thanks for the info. Maybe you should update your wiki. ;)
