### ISSUE TITLE
Incorrect colors

### ISSUE THREAD

**Issue by RafFontaine** [mortaca/RGB-Pi#83]
Hello, I purchased an RGB-Pi scart cable from your website last year and paired it with a Raspberry Pi 4 and the latest Beta build provided at the time, and have since updated each time a new image came out. 
 Unfortunately ever since the beginning I have had the same issue where the red and white colors aren't correct making some games look very off, I have tested in several different Crt tv's from basic kitchen sets to a big Bang & Olufsen monitor and all display the same problem. I have failed to find any guidance online for this particular color issue, since most problems reported are specific to certain TV sets and not mine.
 Is there something I am missing, perhaps a setting in the OS or a change I could make to a config.txt somewhere?

 I am sending photos of the issue in question from the adjustment page in the RGB-Pi OS from two diferent crt's to compare. 

This is a really cool project and I think you guys are doing awesome work, I want to thank you for all you do and any help you can provide is imensely appreciated. 

Best Regards,

Rafael

![20230626_134455](https://github.com/mortaca/RGB-Pi/assets/137795530/22cbb1a9-6f3d-4851-b137-32443a2ed750)
![20230626_132357](https://github.com/mortaca/RGB-Pi/assets/137795530/78a0dfdd-cb9b-4cde-a5d0-a1ee61c8ca15)

**Comment by rtomasa** [comment]
Please go to the official Telegram channel for support: t.me/rgb_pi
There you can ask again and we will happily help you
